# Generated by Django 5.1.6 on 2025-03-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_alter_agendamento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='prioritario',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Prioritário'),
        ),
    ]
