# Generated by Django 5.1.6 on 2025-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Contato'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_person',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Pessoal'),
        ),
    ]
