# Generated by Django 5.1.6 on 2025-03-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_phone_userprofile_phone_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_person',
            field=models.CharField(default=5656565656, max_length=15, verbose_name='Telefone Pessoal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretary', 'Secretario'), ('interviewer', 'Entrevistador'), ('client', 'Cliente')], default='client', max_length=20),
        ),
    ]
