# Generated by Django 5.1.6 on 2025-03-06 03:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('atributo1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Atributo 1')),
                ('atributo2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Atributo 2')),
                ('atributo3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Atributo 3')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo'), ('menor', 'Menor de Idade')], max_length=10, verbose_name='Estado Civil')),
                ('horario', models.TextField(verbose_name='Horário')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Agendamento')),
                ('rg_frente', models.ImageField(blank=True, null=True, upload_to='documentos/rg/', verbose_name='RG (Frente)')),
                ('rg_verso', models.ImageField(blank=True, null=True, upload_to='documentos/rg/', verbose_name='RG (Verso)')),
                ('cpf_documento', models.ImageField(blank=True, null=True, upload_to='documentos/cpf/', verbose_name='CPF')),
                ('certidao_nascimento', models.ImageField(blank=True, null=True, upload_to='documentos/certidoes/', verbose_name='Certidão de Nascimento')),
                ('certidao_casamento', models.ImageField(blank=True, null=True, upload_to='documentos/certidoes/', verbose_name='Certidão de Casamento')),
                ('certidao_casamento_averbada', models.ImageField(blank=True, null=True, upload_to='documentos/certidoes/', verbose_name='Certidão de Casamento Averbada')),
                ('certidao_obito', models.ImageField(blank=True, null=True, upload_to='documentos/certidoes/', verbose_name='Certidão de Óbito')),
                ('autorizacao_pais', models.ImageField(blank=True, null=True, upload_to='documentos/autorizacoes/', verbose_name='Autorização dos Pais/Responsáveis')),
                ('comprovante_residencia', models.ImageField(blank=True, null=True, upload_to='documentos/comprovantes/', verbose_name='Comprovante de Residência')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico', verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now, verbose_name='Data')),
                ('vagas', models.PositiveIntegerField(default=1, verbose_name='Vagas')),
                ('hora_inicio', models.TimeField(default=datetime.datetime.now, verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(default=datetime.datetime.now, verbose_name='Hora de Fim')),
                ('intervalo', models.PositiveIntegerField(default=30, verbose_name='Intervalo')),
                ('horarios_disponiveis', models.JSONField(blank=True, default=list, verbose_name='Horários disponíveis')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='disponivel', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico', verbose_name='Serviço')),
            ],
        ),
    ]
