# Generated by Django 5.1.6 on 2025-03-06 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servico_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienteAgendamento',
            new_name='Agendar',
        ),
    ]
