# Generated by Django 5.1.6 on 2025-03-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_rename_clienteagendamento_agendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='servico',
            field=models.TextField(verbose_name='Serviço'),
        ),
    ]
