# Generated by Django 5.1.6 on 2025-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_agendar_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='servico',
            field=models.TextField(blank=True, null=True, verbose_name='Serviço'),
        ),
    ]
