# Generated by Django 5.1.6 on 2025-03-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_alter_agendar_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='data_agendamento',
            field=models.DateTimeField(verbose_name='Data do Agendamento'),
        ),
    ]
