# Generated by Django 5.1.6 on 2025-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_alter_agendar_data_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='agendar',
            name='compareceu',
            field=models.BooleanField(default=False, verbose_name='Compareceu'),
        ),
        migrations.AddField(
            model_name='agendar',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
    ]
