# Generated by Django 5.1.6 on 2025-03-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_agendar_cancelado_agendar_compareceu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='senha',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Senha'),
        ),
    ]
