# Generated by Django 5.1.6 on 2025-03-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_servicos_delete_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendar',
            name='autorizacao_pais',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='certidao_casamento',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='certidao_casamento_averbada',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='certidao_nascimento',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='certidao_obito',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='comprovante_residencia',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='cpf_documento',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='rg_frente',
        ),
        migrations.RemoveField(
            model_name='agendar',
            name='rg_verso',
        ),
    ]
