# Generated by Django 5.1.6 on 2025-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0010_remove_agendar_autorizacao_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='agendado',
            field=models.BooleanField(default=False, verbose_name='Agendado'),
        ),
    ]
